#!/bin/sh

printf "%s                    -@"
printf "%s                   .##@"
printf "%s                  .####@"
printf "%s                  @#####@"
printf "%s                . *######@"
printf "%s               .##@o@#####@"
printf "%s              /############@"
printf "%s             /##############@"
printf "%s            @######@**%######@"
printf "%s           @######`     %#####o"
printf "%s          @######@       ######%"
printf "%s        -@#######h       ######@.`"
printf "%s       /#####h**``       `**%@####@"
printf "%s      @H@*`                    `*%#@"
printf "%s     *`                            `*"