#!/bin/bash

# ======================================================================#
# >>>           VARIÁVEIS
# ----------------------------------------------------------------------#

# --- COLORS
  Bold=$(tput bold)
  Underline=$(tput sgr 0 1)
  Reset=$(tput sgr0)
  # Regular Colors
  Red=$(tput setaf 1)
  Green=$(tput setaf 2)
  Yellow=$(tput setaf 3)
  Blue=$(tput setaf 4)
  Purple=$(tput setaf 5)
  Cyan=$(tput setaf 6)
  White=$(tput setaf 7)
  # Bold
  BRed=${Bold}${Red}
  BGreen=${Bold}${Green}
  BYellow=${Bold}${Yellow}
  BBlue=${Bold}${Blue}
  BPurple=${Bold}${Purple}
  BCyan=${Bold}${Cyan}
  BWhite=${Bold}${White}

# ====================================================================== #
# >>>           FUNÇÕES PRINCIPAIS
# ---------------------------------------------------------------------- #

install_official_repo_pkgs() {
  print_title "INSTALANDO PACOTES EXTRAS DO REPOSITÓRIO OFICIAL..."
  pacman -S --needed --noconfirm \
    libreoffice-fresh \
    libreoffice-fresh-pt-br \
    firefox \
    firefox-i18n-pt-br \
    steam \
    gimp \
    inkscape \
    virtualbox \
    virtualbox-host-dkms \
    virtualbox-guest-iso \
    vlc \
    telegram-desktop \
    simplescreenrecorder \
    redshift \
    adapta-gtk-theme \
    arc-gtk-theme \
    papirus-icon-theme \
    capitaine-cursors \
    ttf-dejavu
  print_warning " CONCLUÍDO!"
  pause_function
}

install_aur_pkgs() {
  print_title "INSTALANDO PACOTES EXTRAS DO REPOSITÓRIO OFICIAL..."
  pamac build --no-confirm \
    google-chrome \
    spotify    
  print_warning " CONCLUÍDO!"
  pause_function
}

# ======================================================================#
# >>>           OUTRAS FUNÇÕES
# ----------------------------------------------------------------------#

print_line() {
  printf "%$(tput cols)s\n"|tr ' ' '-'
}

print_title() {
  clear
  print_line
  echo -e "${BPurple}# $1${Reset}"
  print_line
  echo ""
}

print_warning() {
  T_COLS=$(tput cols)
  echo -e "\n${BGreen}$1${Reset}\n" | fold -sw $(( T_COLS - 1 ))
}

pause_function() { #{{{
  print_line
  read -e -sn 1 -p "Pressione qualquer tecla para continuar..."
}

# ====================================================================== #
# >>>           INSTALAÇÃO
# ---------------------------------------------------------------------- #
